### ISSUE TITLE
Magic constant

### ISSUE THREAD

**Issue by marcfedorow** [Chubru/lab#2]
https://github.com/Chubru/lab/blob/d9d1344947ea7b94d94127b0568a7232ab8571d8/Lab_4/lab_4.cpp#L10

Use `tolower(c)`

**Comment by Chubru** [comment]
данное выражение, используя свойство таблицы ASCII(заглавные буквы отличаются от строчных наличием взведенным 5 битом ) преобразовывать строчные в заглавные.
